### ISSUE TITLE
Get Data Input from a CSV file

### ISSUE THREAD

**Issue by omii2k01** [omii2k01/colist#3]
Writing Markdown for every company would be quite repititive. Instead take data from csv and render it on the page somehow. Still need to think of a good solution.

**Comment by jayoswal** [comment]
How about host a page on github[dot]io whose source code links to repositiory, which can be updated via continuous integration.

**Comment by omii2k01** [comment]
The CI/CD pipeline currently runs automatically once any changes are made to a file in the repository. The application is deployed to https://omii2k01.github.io/colist/ wherein the data can readily be accessed a.k.a the website is already live
